### PR TITLE
Rename all modules to cve2

### PR DESCRIPTION
**Pull request by christian-herber-nxp**
renaming from ibex to cve2

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
Hi @christian-herber-nxp, thanks for this pull-request.  I have assigned @davideschiavone as a reviewer as well.  The changes look good to me, although I will defer to Davide for a final approval.  Note that the CI lint checks are reporting multiple issues.  AFAIK, these are in keeping with the SystemVerilog RTL coding style that OpenHW uses, so we may want to resolve these.  I suspect that these lint violations were created before the lowRISC team adopted the lint checks, so they have been "grandfathered" for Ibex.  (Again, I will defer to Davide on this.)

**Comment by davideschiavone** [comment]
Hi @christian-herber-nxp, thanks for the contribution.

**Review by davideschiavone — APPROVED** [review]

**Comment by davideschiavone** [comment]
@MikeOpenHWGroup , @christian-herber-nxp , this is a decision for the CVE2 team to make, shall I remove the github-action bot that reviews the PR for the style? If not, those issues must be resolved. It is up to the team whether to adopt these rules or not.

**Comment by christian-herber-nxp** [comment]
> @MikeOpenHWGroup , @christian-herber-nxp , this is a decision for the CVE2 team to make, shall I remove the github-action bot that reviews the PR for the style? If not, those issues must be resolved. It is up to the team whether to adopt these rules or not.

i discussed this with szymon. there is little value in refoctoring this code to match some style guide, especially in such a search and replace change. i think it makes sense to have such a check in place, but we shouldnt focus on asthetics at this point of the project. 

is this just a warning or does it block a PR?

**Comment by MikeOpenHWGroup** [comment]
> i discussed this with szymon. there is little value in refoctoring this code to match some style guide, especially in such a search and replace change. i think it makes sense to have such a check in place, but we shouldnt focus on asthetics at this point of the project.

Agreed.

> is this just a warning or does it block a PR?

AFAIK, it is a warning and does not block the merge.

With @davideschiavone's approval the only thing blocking this PR from being merged are the conflicts.

**Comment by davideschiavone** [comment]
> > i discussed this with szymon. there is little value in refoctoring this code to match some style guide, especially in such a search and replace change. i think it makes sense to have such a check in place, but we shouldnt focus on asthetics at this point of the project.
> 
> Agreed.
> 
> > is this just a warning or does it block a PR?
> 
> AFAIK, it is a warning and does not block the merge.
> 
> With @davideschiavone's approval the only thing blocking this PR from being merged are the conflicts.

I actually approved:)

**Comment by christian-herber-nxp** [comment]
@davideschiavone : We resolved some conflicts from a different PR. can you give this a final check and merge?

**Pull request merged**
