### PR TITLE
Feature/prepare documentation

### PR DESCRIPTION
**Pull request by christian-herber-nxp**
This PR adds the technical specification of CV32E20 to the documentation. The original documentation of Ibex is kept and subject to future work.
Also, a readme.md was added in the doc directory, which has the instructions for building the documentation.

### CODE REVIEW

**Comment by christian-herber-nxp** [comment]
Please see if you are able to build the documentation using the instructions in the Readme.

**Comment by DBees** [comment]
@christian-herber-nxp could not build on windows. Will try on linux

**Comment by DBees** [comment]
@christian-herber-nxp due to a problem on my computer I was not able to test the linux build, will be able to do that tomorrow. However I noticed you are missing the .readthedocs.yaml configuration file in the top level of the repo. You can copy this one https://github.com/openhwgroup/core-v-mcu-devkit/blob/main/.readthedocs.yaml. Can you please push that in, then we will merge this PR and see if it builds on the read the docs site.

**Comment by christian-herber-nxp** [comment]
> @christian-herber-nxp due to a problem on my computer I was not able to test the linux build, will be able to do that tomorrow. However I noticed you are missing the .readthedocs.yaml configuration file in the top level of the repo. You can copy this one https://github.com/openhwgroup/core-v-mcu-devkit/blob/main/.readthedocs.yaml. Can you please push that in, then we will merge this PR and see if it builds on the read the docs site.

Thanks, updated the PR

**Review by MikeOpenHWGroup — APPROVED** [review]

**Comment by MikeOpenHWGroup** [comment]
LGTM @christian-herber-nxp.  I will defer to @DBees for the final merge.

**Pull request merged**
